# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 55201ebe0ce1bcc7d5e3f9d339f547459ed02c5ec6dd0d44f21adfc8e0eae783012c92bc355f33f0e21bcacd73117556bd732b73da4a08d927f9c4964a936ff0

test:
  secret_key_base: abc07282430434333d7f19e813d2974910d8af4c09cf6f7ebacafdf76cca0e641dc92d1f396657b893338853cdc96e22156403c74d53d7ac32a932e2f779e538

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
