# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 43dc1889e1749304370e1bcb2f79bcb0850af0b76bca98d9c6d85ed555761a830ad0bde55d317e0f32b18e8357a3b88838eedddabb6bdbac4973cc64b1e15a05

test:
  secret_key_base: 1fa8c0551465cb05570fd9a7e856c90d2ca2bba51ba0cdfb7ffa61b77e4e382d0e4e6b129c76a183f85ed044b625c78e089200be315f92c10efe9a194b93e18c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
